name: build-ecp-veloc-component
description: checkout, build, and install named ecp-veloc component

inputs:
  component:
    description: 'component name'
    required: true
  mpi:
    description: 'MPI status'
    required: false
    default: par
  shared:
    description: 'enable build of shared library: build-shared, build-static'
    required: false
    default: build-shared
  static:
    description: 'link binaries to which lib: link-shared, link-static'
    required: false
    default: link-shared
  ref:
    description: 'SHA or tag to checkout'
    required: false
    default: ''


runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: ecp-veloc/${{ inputs.component }}
        path: ${{ inputs.component }}
        ref: ${{ inputs.ref }}

    - name: build and install
      shell: bash
      run: |
        mkdir -p install
        cd ${{ inputs.component }}
        mkdir build
        cd build
        cmake ../ -DMPI=${{ inputs.mpi == 'par' }} -DBUILD_SHARED_LIBS=${{ inputs.shared == 'build-shared' }} -D$(echo ${{ inputs.component }} | tr 'a-z' 'A-Z')_LINK_STATIC=${{ inputs.static == 'link-static' }} -DCMAKE_INSTALL_PREFIX=../../install
        make
        make install
