name: build-ecp-veloc-component
description: build ecp-veloc component

inputs:
  component:
    description: 'component name'
    required: true
  mpi:
    description: 'MPI status'
    required: false
    default: par

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: ecp-veloc/${{ inputs.component }}
        path: ${{ inputs.component }}

    - name: build and install
      shell: bash
      run: |
        mkdir -p install
        cd ${{ inputs.component }}
        mkdir build
        cd build
        cmake ../ -DMPI=${{ inputs.mpi == 'par' }} -DCMAKE_INSTALL_PREFIX=../../install
        make
        make install
