name: spack-release
description: update the spack package with a new version

inputs:
  component:
    description: 'component name'
    required: true

runs:
  using: "composite"
  steps:
    - name: echo config
      shell: bash
      run: |
        echo "Running ecp-veloc/github-actions/spack-release@main with:"
        echo "${{ inputs.component }}"

    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: spack/spack

    - name: update package release
      shell: bash
      run: |
        echo `bin/spack versions --new ${{ inputs.component }} | tail -n +2`
        verhash=`bin/spack checksum --latest ${{ inputs.component }} | tac | head -n 2 | tail -n 1`
        echo $verhash
        pkgfile="$(bin/spack location -p ${{ inputs.component }})/package.py"
        awk -v newver="$verhash" '/version\('\"'main/ {print; print newver; next} {print;}' $pkgfile >> tmp-${{ inputs.component }}-package.py
        mv tmp-${{ inputs.component }}-package.py $pkgfile
        cat $pkgfile

    - name: verify spack fetch
      shell: bash
      run: |
        bin/spack fetch ${{ inputs.component }}

    - name: commit and push update
      shell: bash
      run: |
        git status
        git diff
        git checkout -b release-${{ inputs.component }}-`date "+%Y%m%d"`
        git config user.email "ecp-veloc@users.noreply.github.com"
        git config user.name  "ECP Veloc GitHub Action"
        git commit -am "new release for ${{ inputs.component }}"
        git remote add ecpv https://github.com/ecp-veloc/spack
        git push ecpv release-${{ inputs.component }}
        echo "Don't forget to create the spack PR"
