name: get-scr-os-deps
description: os install of pdsh, lcov, and optionally mpi

inputs:
  os:
    description: 'os'
    required: true
  mpi:
    description: 'MPI status'
    required: false
    default: par
  autotools:
    description: 'install autotools'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: echo config
      shell: bash
      run: |
        echo "Running ecp-veloc/github-actions/get-scr-os-deps@main with:"
        echo "${{ inputs.os }}"
        echo "${{ inputs.mpi }}"
        echo "${{ inputs.autotools }}"

    - name: get pdsh lcov (Linux)
      if: startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get install pdsh
        sudo apt-get install lcov

    - name: get mpi (Linux)
      if: inputs.mpi == 'par' && startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get install mpich libmpich-dev

    - name: Set up Homebrew
      if: startsWith(inputs.os, 'macos')
      uses: Homebrew/actions/setup-homebrew@master

    - name: get lcov pdsh (MacOS)
      if: startsWith(inputs.os, 'macos')
      shell: bash
      run: |
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        brew install lcov
        brew install pdsh

    - name: get MPI (MacOS)
      if: inputs.mpi == 'par' && startsWith(inputs.os, 'macos')
      shell: bash
      run: |
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        brew install openmpi

    - name: install autotools (MacOS)
      if: inputs.autotools && startsWith(inputs.os, 'macos')
      shell: bash
      run: |
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        brew install libtool autoconf automake
