name: cmake-build-only
description: build only with cmake

inputs:
  component:
    description: 'component name'
    required: true
  target:
    description: 'CMake Build Type'
    required: false
    default: Release
  cmake_line:
    description: 'Additional CMake build options'
    required: false
    default: ""

runs:
  using: "composite"
  steps:

    - name: build
      shell: bash
      run: |
        mkdir build
        mkdir -p install
        cd build
        cmake ../${{ inputs.component }} -DCMAKE_BUILD_TYPE=${{ inputs.target }} -DCMAKE_INSTALL_PREFIX=../install ${{ inputs.cmake_line }}
        make
